Бонуs (не робит но там много измененилось)
Plurimum/MetOptLab3Java pull request #3
Opened 2021-05-20 02:08 UTC by jerxma-git

Я добавил бонус, он выдает неверный результат, но мб просто тесты криво написаны.
Там очень много поменялось в остальных файлах, и надо понимать больно это или норм.

2021-05-20 21:45 UTC, Plurimum requested changes

2021-05-20 21:45 UTC, Plurimum commented on core/src/com/mygdx/linear/CgmSoleFunction.java
> +    @Override
почему просто не переопределить multiply

2021-05-20 21:45 UTC, Plurimum commented on core/src/com/mygdx/nmethods/CGMFunction.java
> +    Vector matVecProd(Vector p);
multiply

2021-05-20 21:45 UTC, Plurimum commented on core/src/com/mygdx/linear/CgmSoleFunction.java
> +    CSRMatrix a;
кто такой `CSRMatrix` и почему не просто `Matrix`

2021-05-20 21:45 UTC, Plurimum commented on core/src/com/mygdx/nmethods/NonlinearConjugateGradientMethod.java
> +public class NonlinearConjugateGradientMethod<F extends CGMFunction> extends QuadraticMethod<F> {
правда ли, что можно было бы просто `CGMFunction` отнаследовать от `QuadraticFunction` и не пришлось бы менять старый код

2021-05-20 21:45 UTC, Plurimum commented on core/src/com/mygdx/nmethods/QuadraticMethod.java
> +public abstract class QuadraticMethod<F extends CGMFunction> extends AbstractNMethod<F> {
менять код в абстрактном классе - совсем грустно

2021-05-21 15:24 UTC, jerxma-git commented on core/src/com/mygdx/linear/CgmSoleFunction.java
> +    CSRMatrix a;
CSR это матрица сжатая по строкам. Если переопределить `multiply`, то можно поменять на `Matrix`

2021-05-21 15:25 UTC, jerxma-git commented on core/src/com/mygdx/nmethods/NonlinearConjugateGradientMethod.java
> +public class NonlinearConjugateGradientMethod<F extends CGMFunction> extends QuadraticMethod<F> {
Нерпавда, потому что там `final` поля a,b,c и тп, которых не должно быть в `реализациях CGMFunction`.
(ну либо я не понимаю как это реализовать)

2021-05-21 15:26 UTC, jerxma-git commented on core/src/com/mygdx/nmethods/QuadraticMethod.java
> +public abstract class QuadraticMethod<F extends CGMFunction> extends AbstractNMethod<F> {
без этого я хз как

2021-05-21 15:27 UTC, jerxma-git commented on core/src/com/mygdx/linear/CgmSoleFunction.java
> +    @Override
я тупа не заметил что в `Matrix` есть `multiply`

2021-05-21 20:21 UTC, merged